name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Install CERN ROOT
      run: |
        wget https://root.cern/download/root_v6.36.04.Linux-almalinux9.6-x86_64-gcc11.5.tar.gz
        tar -xzvf root_v6.36.04.Linux-almalinux9.6-x86_64-gcc11.5.tar.gz
      shell: bash
      
    - name: Setup ROOT environment
      shell: bash
      run: |
        source /home/runner/work/tmd-eic-ana/tmd-eic-ana/root/bin/thisroot.sh
        echo "ROOTSYS is $ROOTSYS"

    - name: Build the project
      run: |
        source $PWD/root/bin/thisroot.sh
        make
      shell: bash

    - name: Run tests
      run: |
        source $PWD/root/bin/thisroot.sh
        ./test_load_tables
      shell: bash