name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install deps + ROOT
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential wget libtbb-dev libyaml-cpp-dev
          wget -q https://root.cern/download/root_v6.36.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
          tar -xzf root_v6.36.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz

      - name: Build
        run: |
          source $GITHUB_WORKSPACE/root/bin/thisroot.sh
          make

      - name: Generate pseudodata + run tests
        run: |
          source $GITHUB_WORKSPACE/root/bin/thisroot.sh
          ./bin/generate_pseudodata
          make tests
          make run-tests

      - name: Run 1D plotting test
        run: |
          source $GITHUB_WORKSPACE/root/bin/thisroot.sh
          mkdir -p artifacts/
          ./bin/test_1D_plots --file out/output.root --tree tree --energy 0x0 --outDir artifacts/
  
      - name: Run 2D plotting test
        run: |
          source $GITHUB_WORKSPACE/root/bin/thisroot.sh
          mkdir -p artifacts/
          ./bin/test_2D_plots --file out/output.root --tree tree --energy 0x0 --outDir artifacts/

      - name: Run Injection test
        run: |
          source $GITHUB_WORKSPACE/root/bin/thisroot.sh
          mkdir -p artifacts/
          ./bin/test_injectExtract --file out/output.root --tree tree --energy 0x0 --outDir artifacts/ --n_injections 25
  
  

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: artifacts/


