name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Install CERN ROOT
      run: |
        wget https://root.cern/download/root_v6.30.06.Linux-ubuntu22-x86_64-gcc11.4.tar.gz
        tar -xzf root_v6.30.06.Linux-ubuntu22-x86_64-gcc11.4.tar.gz
        echo "source $PWD/root/bin/thisroot.sh" >> $GITHUB_ENV
      shell: bash

    - name: Build the project
      run: |
        source $PWD/root/bin/thisroot.sh
        make
      shell: bash

    - name: Run tests
      run: |
        source $PWD/root/bin/thisroot.sh
        ./test_load_tables
      shell: bash