name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, generate data, and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget libtbb-dev
      shell: bash

    - name: Install CERN ROOT
      run: |
        # download a prebuilt ROOT binary compatible with ubuntu-22.04
        wget -q https://root.cern/download/root_v6.36.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
        tar -xzf root_v6.36.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
        ls -la root || true
      shell: bash

    - name: Show ROOT info
      run: |
        # Use GITHUB_WORKSPACE for a portable path to the checked-out repo
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        source "$GITHUB_WORKSPACE/root/bin/thisroot.sh"
        echo "ROOTSYS is $ROOTSYS"
        root-config --version || true
      shell: bash

    - name: Build the project
      run: |
        source "$GITHUB_WORKSPACE/root/bin/thisroot.sh"
        make
      shell: bash

    - name: Generate pseudodata
      run: |
        source "$GITHUB_WORKSPACE/root/bin/thisroot.sh"
        ./bin/generate_pseudodata
      shell: bash

    - name: Run tests
      run: |
        source "$GITHUB_WORKSPACE/root/bin/thisroot.sh"
        make test
      shell: bash